# Clustering Crypto

In [112]:
# Initial imports
import numpy
import pandas as pd
import hvplot.pandas
from pathlib import Path
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans


### Deliverable 1: Preprocessing the Data for PCA

In [79]:
# Load the crypto_data.csv dataset.
file_path = Path('crypto_data.csv')
crypto_df = pd.read_csv(file_path, index_col=0)
crypto_df.head()

CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [80]:
# Keep all the cryptocurrencies that are being traded.
crypto_df = crypto_df[crypto_df.IsTrading == True]
crypto_df.head()

CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [81]:
# Remove the "IsTrading" column. 
crypto_df = crypto_df.drop(columns=['IsTrading'])
crypto_df.head()

CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
365    365Coin       X11   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       PoW              NaN          611000
808        808   SHA-256   PoW/PoS     0.000000e+00               0

In [82]:
# Remove rows that have at least 1 null value.
crypto_df = crypto_df.dropna(axis=0, how="any")
crypto_df.head()

CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
404     404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
808         808   SHA-256   PoW/PoS     0.000000e+00               0
1337  EliteCoin       X13   PoW/PoS     2.927942e+10    314159265359
BTC     Bitcoin   SHA-256       PoW     1.792718e+07        21000000

In [83]:
# Keep the rows where coins are mined
crypto_df.drop(crypto_df[crypto_df["TotalCoinsMined"] <= 0].index, inplace = True)
crypto_df.head()


CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
404     404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
1337  EliteCoin       X13   PoW/PoS     2.927942e+10    314159265359
BTC     Bitcoin   SHA-256       PoW     1.792718e+07        21000000
ETH    Ethereum    Ethash       PoW     1.076842e+08               0

In [84]:
# Create a new DataFrame that holds only the cryptocurrencies names.
cc_names_df = crypto_df["CoinName"].to_frame()
cc_names_df.head()


CoinName
42      42 Coin
404     404Coin
1337  EliteCoin
BTC     Bitcoin
ETH    Ethereum

In [85]:
# Drop the 'CoinName' column since it's not going to be used on the clustering algorithm.
crypto_df = crypto_df.drop(["CoinName"], axis=1)
crypto_df.head()


Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      Scrypt   PoW/PoS     4.199995e+01              42
404     Scrypt   PoW/PoS     1.055185e+09       532000000
1337       X13   PoW/PoS     2.927942e+10    314159265359
BTC    SHA-256       PoW     1.792718e+07        21000000
ETH     Ethash       PoW     1.076842e+08               0

In [86]:
# Use get_dummies() to create variables for text features.
X = pd.get_dummies(crypto_df, columns = ["Algorithm", "ProofType"])
X

TotalCoinsMined TotalCoinSupply  Algorithm_1GB AES Pattern Search  \
42       4.199995e+01              42                                 0   
404      1.055185e+09       532000000                                 0   
1337     2.927942e+10    314159265359                                 0   
BTC      1.792718e+07        21000000                                 0   
ETH      1.076842e+08               0                                 0   
...               ...             ...                               ...   
ZEPH     2.000000e+09      2000000000                                 0   
GAP      1.493105e+07       250000000                                 0   
BDX      9.802226e+08      1400222610                                 0   
ZEN      7.296538e+06        21000000                                 0   
XBC      1.283270e+05         1000000                                 0   

      Algorithm_536  Algorithm_Argon2d  Algorithm_BLAKE256  Algorithm_Blake  \
42                0                  0                   0                0   
404               0                  0                   0                0   
1337              0                  0                   0                0   
BTC               0                  0                   0                0   
ETH               0                  0                   0                0   
...             ...                ...                 ...              ...   
ZEPH              0                  0                   0                0   
GAP               0                  0                   0                0   
BDX               0                  0                   0                0   
ZEN               0                  0                   0                0   
XBC               0                  0                   0                0   

      Algorithm_Blake2S  Algorithm_Blake2b  Algorithm_C11  ...  \
42                    0                  0              0  ...   
404                   0                  0              0  ...   
1337                  0                  0              0  ...   
BTC                   0                  0              0  ...   
ETH                   0                  0              0  ...   
...                 ...                ...            ...  ...   
ZEPH                  0                  0              0  ...   
GAP                   0                  0              0  ...   
BDX                   0                  0              0  ...   
ZEN                   0                  0              0  ...   
XBC                   0                  0              0  ...   

      ProofType_PoW/PoS  ProofType_PoW/PoS   ProofType_PoW/PoW  \
42                    1                   0                  0   
404                   1                   0                  0   
1337                  1                   0                  0   
BTC                   0                   0                  0   
ETH                   0                   0                  0   
...                 ...                 ...                ...   
ZEPH                  0                   0                  0   
GAP                   1                   0                  0   
BDX                   0                   0                  0   
ZEN                   0                   0                  0   
XBC                   0                   0                  0   

      ProofType_PoW/nPoS  ProofType_Pos  ProofType_Proof of Authority  \
42                     0              0                             0   
404                    0              0                             0   
1337                   0              0                             0   
BTC                    0              0                             0   
ETH                    0              0                             0   
...                  ...            ...                           ...   
ZEPH                   0              0                    

In [87]:
X.dtypes

TotalCoinsMined                     float64
TotalCoinSupply                      object
Algorithm_1GB AES Pattern Search      uint8
Algorithm_536                         uint8
Algorithm_Argon2d                     uint8
                                     ...   
ProofType_Proof of Authority          uint8
ProofType_Proof of Trust              uint8
ProofType_TPoS                        uint8
ProofType_Zero-Knowledge Proof        uint8
ProofType_dPoW/PoW                    uint8
Length: 98, dtype: object

In [88]:
# Standardize the data with StandardScaler().
X_scaled = StandardScaler().fit_transform(X)
X_scaled


array([[-0.11710817, -0.1528703 , -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ],
       [-0.09396955, -0.145009  , -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ],
       [ 0.52494561,  4.48942416, -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ],
       ...,
       [-0.09561336, -0.13217937, -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ],
       [-0.11694817, -0.15255998, -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ],
       [-0.11710536, -0.15285552, -0.0433963 , ..., -0.0433963 ,
        -0.0433963 , -0.0433963 ]])

In [89]:
X_scaled.shape

(532, 98)

### Deliverable 2: Reducing Data Dimensions Using PCA

In [90]:
# Using PCA to reduce dimension to three principal components.
pca = PCA(n_components=3)
crypto_pca = pca.fit_transform(X_scaled)
crypto_pca

array([[-0.33177653,  0.95899731, -0.55146144],
       [-0.31511891,  0.95923537, -0.55155765],
       [ 2.32030704,  1.66836187, -0.54815231],
       ...,
       [ 0.32242178, -2.24820136,  0.3644616 ],
       [-0.16100999, -2.16920019,  0.28109135],
       [-0.30180207,  0.85627287, -0.26811704]])

In [120]:
# Create a DataFrame with the three principal components.
pcs_df = pd.DataFrame(
    data=crypto_pca,
    columns=['PC_1', 
             'PC_2',
             'PC_3'],
    index=X.index
   
)
pcs_df

PC_1      PC_2      PC_3
42   -0.331777  0.958997 -0.551461
404  -0.315119  0.959235 -0.551558
1337  2.320307  1.668362 -0.548152
BTC  -0.134709 -1.276015  0.175844
ETH  -0.147388 -2.031405  0.353951
...        ...       ...       ...
ZEPH  2.498864  0.708020  0.161906
GAP  -0.329824  0.958905 -0.551470
BDX   0.322422 -2.248201  0.364462
ZEN  -0.161010 -2.169200  0.281091
XBC  -0.301802  0.856273 -0.268117

[532 rows x 3 columns]

### Deliverable 3: Clustering Crytocurrencies Using K-Means

#### Finding the Best Value for `k` Using the Elbow Curve

In [92]:
# Find the best value for K
inertia = []
k = list(range(1, 11))

# Calculate the inertia for the range of K values
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(pcs_df)
    inertia.append(km.inertia_)

# Create an elbow curve to find the best value for K.
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")


:Curve   [k]   (inertia)

Running K-Means with `k=4`

In [93]:
# Initialize the K-Means model.
model = KMeans(n_clusters=4, random_state=0)

# Fit the model
model.fit(pcs_df)

# Predict clusters
predictions = model.predict(pcs_df)
predictions


array([0, 0, 0, 3, 3, 3, 0, 3, 3, 3, 0, 3, 0, 0, 3, 0, 3, 3, 0, 0, 3, 3,
       3, 3, 3, 0, 3, 3, 3, 0, 3, 0, 3, 3, 0, 0, 3, 3, 3, 3, 3, 3, 0, 0,
       3, 3, 3, 3, 3, 0, 0, 3, 0, 3, 3, 3, 3, 0, 3, 3, 0, 3, 0, 0, 0, 3,
       3, 3, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 3, 0, 3, 0, 0, 3, 3, 3, 3, 0,
       0, 3, 0, 3, 3, 0, 0, 3, 0, 0, 3, 3, 0, 0, 3, 0, 0, 3, 0, 3, 0, 3,
       0, 3, 0, 0, 3, 3, 0, 3, 3, 3, 0, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 0,
       3, 0, 3, 3, 0, 3, 0, 3, 0, 0, 3, 3, 0, 3, 3, 0, 0, 3, 0, 3, 0, 0,
       0, 3, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
       0, 3, 0, 3, 0, 0, 3, 0, 3, 0, 0, 3, 0, 3, 0, 3, 0, 3, 0, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 3, 3, 0, 0, 3, 3, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 3, 3, 3, 0, 0, 0, 0, 3, 0, 3, 0,
       0, 3, 0, 3, 3, 0, 3, 3, 0, 3, 0, 0, 0, 3, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 3, 0, 3, 0, 0, 0, 0, 3, 0, 3, 0, 3, 3, 3, 3, 0, 3, 0, 0, 3,
       0, 3, 3, 3, 0, 3, 0, 3, 3, 3, 0, 3, 0, 3, 0,

In [94]:
# Create a new DataFrame including predicted clusters and cryptocurrencies features.
# Concatentate the crypto_df and pcs_df DataFrames on the same columns.
clustered_df = crypto_df.join(pcs_df, how="inner")

#  Add a new column, "CoinName" to the clustered_df DataFrame that holds the names of the cryptocurrencies. 
clustered_df["CoinName"]= cc_names_df["CoinName"]

#  Add a new column, "Class" to the clustered_df DataFrame that holds the predictions.
clustered_df["Class"] = model.labels_ 

# Print the shape of the clustered_df
print(clustered_df.shape)

clustered_df.head(10)

(532, 9)


Algorithm ProofType  TotalCoinsMined TotalCoinSupply      PC_1  \
42            Scrypt   PoW/PoS     4.199995e+01              42 -0.331777   
404           Scrypt   PoW/PoS     1.055185e+09       532000000 -0.315119   
1337             X13   PoW/PoS     2.927942e+10    314159265359  2.320307   
BTC          SHA-256       PoW     1.792718e+07        21000000 -0.134709   
ETH           Ethash       PoW     1.076842e+08               0 -0.147388   
LTC           Scrypt       PoW     6.303924e+07        84000000 -0.173380   
DASH             X11   PoW/PoS     9.031294e+06        22000000 -0.380131   
XMR   CryptoNight-V7       PoW     1.720114e+07               0 -0.144069   
ETC           Ethash       PoW     1.133597e+08       210000000 -0.145831   
ZEC         Equihash       PoW     7.383056e+06        21000000 -0.161009   

          PC_2      PC_3          CoinName  Class  
42    0.958997 -0.551461           42 Coin      0  
404   0.959235 -0.551558           404Coin      0  
1337  1.668362 -0.548152         EliteCoin      0  
BTC  -1.276015  0.175844           Bitcoin      3  
ETH  -2.031405  0.353951          Ethereum      3  
LTC  -1.144426 -0.054329          Litecoin      3  
DASH  1.167526 -0.390436              Dash      0  
XMR  -2.171377  0.394907            Monero      3  
ETC  -2.031485  0.353944  Ethereum Classic      3  
ZEC  -2.169200  0.281091             ZCash      3

### Deliverable 4: Visualizing Cryptocurrencies Results

#### 3D-Scatter with Clusters

In [95]:
# Creating a 3D-Scatter with the PCA data and the clusters
# Plot the 3D-scatter with x="Total Coins Mined", y="Total Coins Supply"
fig = px.scatter_3d(
                clustered_df,
                x="PC_1",
                y="PC_2",
                z="PC_3",
                color="Class",
                symbol="Class",
                width=800)
fig.update_layout(legend=dict(x=0,y=1))
fig.show()

In [96]:
# Create a table with tradable cryptocurrencies.
clustered_df.hvplot.table(columns=['CoinName', 'Algorithm', 'ProofType', 'TotalCoinSupply', 'TotalCoinsMined', 'Class'])
clustered_df.head()

Algorithm ProofType  TotalCoinsMined TotalCoinSupply      PC_1      PC_2  \
42      Scrypt   PoW/PoS     4.199995e+01              42 -0.331777  0.958997   
404     Scrypt   PoW/PoS     1.055185e+09       532000000 -0.315119  0.959235   
1337       X13   PoW/PoS     2.927942e+10    314159265359  2.320307  1.668362   
BTC    SHA-256       PoW     1.792718e+07        21000000 -0.134709 -1.276015   
ETH     Ethash       PoW     1.076842e+08               0 -0.147388 -2.031405   

          PC_3   CoinName  Class  
42   -0.551461    42 Coin      0  
404  -0.551558    404Coin      0  
1337 -0.548152  EliteCoin      0  
BTC   0.175844    Bitcoin      3  
ETH   0.353951   Ethereum      3

In [97]:
# Print the total number of tradable cryptocurrencies.
print(f"There are {len(clustered_df)} tradable cryptocurrencies")

There are 532 tradable cryptocurrencies


In [98]:
# Scaling data to create the scatter plot with tradable cryptocurrencies.
crypto_df_scaled = MinMaxScaler().fit_transform(crypto_df[["TotalCoinSupply","TotalCoinsMined"]])
crypto_df_scaled

array([[4.20000000e-11, 0.00000000e+00],
       [5.32000000e-04, 1.06585544e-03],
       [3.14159265e-01, 2.95755135e-02],
       ...,
       [1.40022261e-03, 9.90135079e-04],
       [2.10000000e-05, 7.37028150e-06],
       [1.00000000e-06, 1.29582282e-07]])

In [99]:
# Create a new DataFrame that has the scaled data with the clustered_df DataFrame index.
plot_df = pd.DataFrame(
    data=tradable_df, columns=["TotalCoinSupply","TotalCoinsMined"]
)

# Add the "CoinName" column from the clustered_df DataFrame to the new DataFrame.
plot_df["CoinName"] = clustered_df["CoinName"]

# Add the "Class" column from the clustered_df DataFrame to the new DataFrame. 
plot_df["Class"] = clustered_df["Class"]

plot_df.head()

TotalCoinSupply  TotalCoinsMined   CoinName  Class
42                42     4.199995e+01    42 Coin      0
404        532000000     1.055185e+09    404Coin      0
1337    314159265359     2.927942e+10  EliteCoin      0
BTC         21000000     1.792718e+07    Bitcoin      3
ETH                0     1.076842e+08   Ethereum      3

In [ ]:
# Create a hvplot.scatter plot using x="TotalCoinsMined" and y="TotalCoinSupply"
plot_df.hvplot.scatter(
    x="TotalCoinsMined",
    y="TotalCoinSupply",
    by="class",
    hover_cols=["CoinName"])

